# Generated by Django 2.0.5 on 2018-05-30 05:37

import cover.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cover', '0005_auto_20180527_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolprofile',
            name='image',
            field=models.ImageField(blank=True, upload_to=cover.models.school_image_path),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='website',
            field=models.URLField(blank=True, default=''),
        ),
    ]
