# Generated by Django 2.0.5 on 2018-05-30 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cover', '0006_auto_20180530_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolprofile',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='country',
            field=models.TextField(default='IN'),
        ),
    ]
