# Generated by Django 2.0.5 on 2018-05-30 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='fa_type',
            field=models.TextField(default='fa-star'),
        ),
        migrations.AddField(
            model_name='notification',
            name='link',
            field=models.URLField(default=''),
        ),
    ]
